/**
 * @file      apps/control-center/components/plan-panel.tsx
 * @phase     P11
 * @owner     Product & Experience
 * @purpose   PLAN view: per-cloud ARCHITECTURE CHOICE (with the rationale Bob gave for it vs. the other real option),
 *            resources, env, secret refs, risks, generated assets, rollback, gates, cost.
 * @depends   @bobops/core, ./ui
 * @usedBy    app/run/page.tsx
 * @agentNotes Secret refs render as 🔒 names only — values never reach the UI. The kind badge + rationale are the
 *             centerpiece of this panel: they are the proof that Bob made a real decision, not a fixed mapping.
 */
import { describeService, servicesForProvider, type RunAggregate } from '@bobops/core';
import { Panel, ProviderBadge, SeverityDot } from './ui';

export function PlanPanel({ agg }: { agg: RunAggregate }) {
  const plan = agg.run.plan;
  if (!plan) return null;
  return (
    <Panel
      title="PLAN — synthesized deployment plan"
      subtitle={plan.summary}
      right={<span className="font-mono text-[11px] text-muted">sha256 {agg.run.planHash?.slice(0, 12)}…</span>}
    >
      <div className="grid gap-4 md:grid-cols-2">
        {plan.targets.map((t) => {
          const chosen = describeService(t.service);
          const alternative = servicesForProvider(t.provider).find((s) => s.service !== t.service);
          return (
            <div key={t.provider} className="rounded-lg border border-line bg-canvas p-4">
              <div className="flex items-center justify-between">
                <ProviderBadge provider={t.provider} />
                <span className="font-mono text-xs text-muted">{t.region}</span>
              </div>
              <p className="mt-2 font-mono text-sm font-semibold text-fg">{t.appName}</p>
              <div className="mt-3 flex items-center gap-2">
                <span
                  className={`rounded px-2 py-0.5 text-[10px] font-semibold uppercase tracking-wider ${chosen.kind === 'warm' ? 'bg-ok/15 text-ok border border-ok/30' : 'bg-info/15 text-info border border-info/30'}`}
                >
                  {chosen.kind === 'warm' ? '● always warm' : '◐ cost-optimized'}
                </span>
                <span className="text-xs font-semibold text-fg">{chosen.label}</span>
              </div>
              <p className="mt-2.5 rounded border border-bob/30 bg-bob/5 p-2.5 text-xs leading-relaxed text-fg">
                <span className="font-semibold text-bob">Why this architecture: </span>
                {t.architectureRationale}
              </p>
              {alternative && (
                <p className="mt-1.5 text-[10px] text-muted">
                  Not chosen: <span className="font-mono text-fg">{alternative.label}</span> — {alternative.description}
                </p>
              )}
              <table className="mt-3 w-full text-xs">
                <tbody>
                  {t.resources.map((r) => (
                    <tr key={r.type + r.name} className="border-t border-line/60">
                      <td className="py-1 pr-2 text-muted uppercase text-[10px] font-mono">{r.action}</td>
                      <td className="py-1 pr-2 text-fg">{r.type}</td>
                      <td className="py-1 font-mono text-muted">{r.name}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
              <div className="mt-3.5 flex flex-wrap gap-1.5 border-t border-line/60 pt-2.5">
                {Object.entries(t.env).map(([k, v]) => (
                  <span key={k} className="rounded border border-line bg-layer-2 px-2 py-0.5 font-mono text-[10px] text-fg">
                    {k}={v}
                  </span>
                ))}
                {t.secretRefs.map((s) => (
                  <span key={s} className="rounded border border-bob/30 bg-bob/15 px-2 py-0.5 font-mono text-[10px] text-bob">
                    🔒 {s}
                  </span>
                ))}
              </div>
            </div>
          );
        })}
      </div>
      <div className="mt-5 grid gap-6 text-sm md:grid-cols-3 border-t border-line pt-4">
        <div>
          <h3 className="text-[10px] uppercase tracking-wider text-muted font-medium">Assessed Risks</h3>
          <ul className="mt-2 space-y-2">
            {plan.risks.map((r) => (
              <li key={r.id} className="text-xs">
                <SeverityDot severity={r.severity} />
                <span className="font-medium text-fg">{r.title}</span>
                <p className="mt-0.5 text-[11px] text-muted pl-3.5">↳ {r.mitigation}</p>
              </li>
            ))}
          </ul>
        </div>
        <div>
          <h3 className="text-[10px] uppercase tracking-wider text-muted font-medium">Generated by Bob</h3>
          <ul className="mt-2 space-y-1.5 text-xs">
            {plan.generatedAssets.map((a) => (
              <li key={a.path}>
                <span className="font-mono text-ibm-soft">{a.path}</span> <span className="text-muted">— {a.purpose}</span>
              </li>
            ))}
          </ul>
        </div>
        <div>
          <h3 className="text-[10px] uppercase tracking-wider text-muted font-medium">Rollback &amp; Gates</h3>
          <p className="mt-2 text-xs text-fg">{plan.rollbackStrategy}</p>
          <ul className="mt-2 list-disc pl-4 text-xs text-warn">
            {plan.approvalGates.map((g) => (
              <li key={g}>{g}</li>
            ))}
          </ul>
          {plan.estimatedMonthlyCostUsd !== undefined && (
            <p className="mt-2 text-xs text-muted font-mono">Estimated cost ≈ ${plan.estimatedMonthlyCostUsd}/month</p>
          )}
        </div>
      </div>
    </Panel>
  );
}
