/**
 * @file      apps/demo-service/src/app.ts
 * @phase     P3
 * @owner     Product & Experience
 * @purpose   The Nimbus Books HTTP API (runtime-agnostic): works on Node (Code Engine) and AWS Lambda.
 * @depends   hono, ./config, ./catalog
 * @usedBy    ./server.ts (Node), ./lambda.ts (generated by Bob), ./app.test.ts
 * @agentNotes Config is read PER REQUEST from the env object so tests can inject env. Errors go to console.error so they
 *             appear in Code Engine logs / CloudWatch — Bob's diagnosis cites these lines.
 */
import { Hono } from 'hono';
import { BOOKS } from './catalog';
import { readConfig } from './config';

export function createApp(env: Record<string, string | undefined>): Hono {
  const app = new Hono();
  const startedAt = new Date().toISOString();

  app.get('/', (c) =>
    c.json({ service: 'nimbus-books', message: 'Nimbus Books catalog API', endpoints: ['/health', '/api/books'] }),
  );

  app.get('/health', (c) => {
    const cfg = readConfig(env);
    const ok = cfg.missing.length === 0;
    if (!ok) console.error(`[health] FAIL missing required env: ${cfg.missing.join(', ')}`);
    return c.json(
      {
        status: ok ? 'healthy' : 'unhealthy',
        service: 'nimbus-books',
        revision: cfg.appVersion,
        provider: cfg.provider,
        startedAt,
        checks: {
          config: ok
            ? { ok: true }
            : { ok: false, missing: cfg.missing, hint: 'Set the missing environment variables and redeploy' },
        },
      },
      ok ? 200 : 503,
    );
  });

  app.get('/api/books', (c) => {
    const cfg = readConfig(env);
    if (cfg.missing.length) {
      console.error(`[books] cannot serve catalog: missing ${cfg.missing.join(', ')}`);
      return c.json({ error: 'catalog_unavailable', missing: cfg.missing }, 500);
    }
    const books = cfg.catalogMode === 'featured' ? BOOKS.filter((b) => b.featured) : BOOKS;
    return c.json({ mode: cfg.catalogMode, count: books.length, books });
  });

  app.get('/api/admin/stats', (c) => {
    const cfg = readConfig(env);
    if (!cfg.adminToken || c.req.header('x-admin-token') !== cfg.adminToken) {
      return c.json({ error: 'unauthorized' }, 401);
    }
    return c.json({ books: BOOKS.length, featured: BOOKS.filter((b) => b.featured).length, startedAt });
  });

  return app;
}
